version: '3.7'
services:
    webapp:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "8000:8000"
            - "8001:8001"
            - "8002:8002"
            - "8003:8003"
            - "8004:8004"
        volumes:
            - /Users/xxx/Software/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - /Users/xxx/Software/docker/nginx/conf/conf.d:/etc/nginx/conf.d
            - /Users/xxx/Software/docker/nginx/log:/var/log/nginx
            - /Users/xxx/Software/docker/nginx//html:/usr/share/nginx/html
